# Generated by Django 4.1.3 on 2022-11-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descrição',
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
